### PR TITLE
Add independent functions for better tree shaking

### PR DESCRIPTION
**Pull request by fisker**
I'm trying to introduce this package to Prettier, but the package size is important for us.

So we use a script to manually shake the code we don't need. https://github.com/prettier/prettier/pull/15566/files#diff-6413fde37ca79249dbd02ed830fabbd527b335d7f1d852a0730cb28cbf86d591R1

Even with this change, we still can't get ride of the "ambiguous" parts we don't use. Not sure what's the best.

### CODE REVIEW

**Comment by fisker** [comment]
Do you mind export `isFullWidth` and `isWide`?

**Comment by fisker** [comment]
//cc @sosukesuzuki

**Comment by sindresorhus** [comment]
Did you try adding `sideEffects: false` to package.json here?

**Comment by sindresorhus** [comment]
> Do you mind export isFullWidth and isWide?

I'm open to it if that's the only way to get down the size, but I would prefer if tree-shaking would *just work*, if possible.

**Comment by fisker** [comment]
"ambiguous" part is used in `eastAsianWidth`, I don't think `sideEffects: false` can remove runtime code.

**Comment by fisker** [comment]
A new function like `eastAsianNarrowWidth` only counts "fullwidth" and "wide" will also work for Prettier, the bundlers are able to remove unused `isAmbiguous`.

**Comment by sindresorhus** [comment]
> A new function like eastAsianNarrowWidth only counts "fullwidth" and "wide" will also work for Prettier

Yeah. I'm fine with a `isNarrowWidth()` method.

However, consumers would expect to be able to decide whether "ambigious" is "narrow". So how about we make it `_isNarrowWidth()` just for Prettier's use?

**Comment by fisker** [comment]
Added `_isNarrowWidth`, this PR still support better tree shaking for users only use `eastAsianWidth`, so I'm going to leave the title unchanged.

**Comment by sindresorhus** [comment]
Should I release?

**Comment by sindresorhus** [comment]
Sidenote: When you target Node.js 20 next year, you'll be able to remove the `emoji-regex` dependency.

```js
/\p{RGI_Emoji}/v
```

**Comment by fisker** [comment]
> Should I release?

Yes, please

**Comment by fisker** [comment]
> When you target Node.js 20 next year, you'll be able to remove the `emoji-regex` dependency.

We still support 14. That's why we are not using `string-width` 😄

**Pull request merged**
