### PR TITLE
Simplify

### PR DESCRIPTION
**Pull request by fisker**

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's intentionally generating if statements as that should be faster to run as it's easier for the JIT to optimize, at least in theory.

**Comment by sindresorhus** [comment]
Nice! Will take a closer look and merge when I'm back at my computer.

**Comment by fisker** [comment]
Are you taking about removed `if`s in #2?
This one didn't.

In this PR, removed use of "A", "F", "H", "N", "Na", "W", and use the long category name directly.

**Comment by sindresorhus** [comment]
No, just misread the diff. Also why I should not review on the phone.

**Comment by fisker** [comment]
:smile: I should not change the hex to upper case in this one... Thought it's good to let it satisfy [`number-literal-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/number-literal-case.md).

**Comment by sindresorhus** [comment]
> Thought it's good to let it satisfy [number-literal-case](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/number-literal-case.md).

👍

**Pull request merged**
